### ISSUE TITLE
RTSS_Reader

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/Dicom-To-CNN#41]
Renommer RTSS_Reader en Instance_RTSS
Cette classe doit heriter de Instance (pour la partie commune a tous les DICOM) et ajoute les méthode spécifiques aux RTSS.

Dans le model mettre un sous repertoire "reader" pour y mettre les classe qui lisent les dicom Instance et Instance_RTSS

**Comment by salimkanoun** [comment]
RTSS reader ovveride get_image_nparray et renvoi une execption (non applicable pour RTSS)

**Comment by wendyrvllr** [comment]
done
